name: Deploy Quartz site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Quartz repository
        uses: actions/checkout@v7

      - name: Checkout content repository
        uses: actions/checkout@v7
        with:
          repository: semsig13-tech/TDOC
          token: ${{ secrets.ACCESS_TOKEN }}
          path: content

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 22          # ✅ изменено с 20 на 22
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build site
        run: npx quartz build --directory ./content

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
